# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/mystul/setup-makefiles.sh

PRODUCT_COPY_FILES += \
        vendor/htc/mystul/proprietary/bin/charging:/system/bin/charging \
        vendor/htc/mystul/proprietary/bin/thermald:/system/bin/thermald \
        vendor/htc/mystul/proprietary/bin/mpdecision:/system/bin/mpdecision \
        vendor/htc/mystul/proprietary/bin/rmt_storage:/system/bin/rmt_storage \
        vendor/htc/mystul/proprietary/bin/qseecomd:/system/bin/qseecomd \
        vendor/htc/mystul/proprietary/lib/libQSEEComAPI.so:/system/lib/libQSEEComAPI.so \
        vendor/htc/mystul/proprietary/etc/agps_rm:/system/etc/agps_rm \
        vendor/htc/mystul/proprietary/lib/libloc_api_v02.so:/system/lib/libloc_api_v02.so \
        vendor/htc/mystul/proprietary/vendor/firmware/keymaster/keymaster.b00:/system/vendor/firmware/keymaster/keymaster.b00 \
        vendor/htc/mystul/proprietary/vendor/firmware/keymaster/keymaster.b01:/system/vendor/firmware/keymaster/keymaster.b01 \
        vendor/htc/mystul/proprietary/vendor/firmware/keymaster/keymaster.b02:/system/vendor/firmware/keymaster/keymaster.b02 \
        vendor/htc/mystul/proprietary/vendor/firmware/keymaster/keymaster.b03:/system/vendor/firmware/keymaster/keymaster.b03 \
        vendor/htc/mystul/proprietary/vendor/firmware/keymaster/keymaster.mdt:/system/vendor/firmware/keymaster/keymaster.mdt \
        vendor/htc/mystul/proprietary/etc/firmware/BCM4334B0_002.001.013.1352.1458.hcd:/system/etc/firmware/BCM4334B0_002.001.013.1352.1458.hcd \
        vendor/htc/mystul/proprietary/etc/firmware/a300_pfp.fw:/system/etc/firmware/a300_pfp.fw \
        vendor/htc/mystul/proprietary/etc/firmware/a300_pm4.fw:/system/etc/firmware/a300_pm4.fw \
        vendor/htc/mystul/proprietary/etc/firmware/fw_bcm4334.bin:/system/etc/firmware/fw_bcm4334.bin \
        vendor/htc/mystul/proprietary/etc/firmware/fw_bcm4334_apsta.bin:/system/etc/firmware/fw_bcm4334_apsta.bin \
        vendor/htc/mystul/proprietary/etc/firmware/fw_bcm4334_p2p.bin:/system/etc/firmware/fw_bcm4334_p2p.bin \
        vendor/htc/mystul/proprietary/etc/firmware/hcheck.b00:/system/etc/firmware/hcheck.b00 \
        vendor/htc/mystul/proprietary/etc/firmware/hcheck.b01:/system/etc/firmware/hcheck.b01 \
        vendor/htc/mystul/proprietary/etc/firmware/hcheck.b02:/system/etc/firmware/hcheck.b02 \
        vendor/htc/mystul/proprietary/etc/firmware/hcheck.b03:/system/etc/firmware/hcheck.b03 \
        vendor/htc/mystul/proprietary/etc/firmware/hcheck.mdt:/system/etc/firmware/hcheck.mdt \
        vendor/htc/mystul/proprietary/etc/firmware/tzapps.b00:/system/etc/firmware/tzapps.b00 \
        vendor/htc/mystul/proprietary/etc/firmware/tzapps.b01:/system/etc/firmware/tzapps.b01 \
        vendor/htc/mystul/proprietary/etc/firmware/tzapps.b02:/system/etc/firmware/tzapps.b02 \
        vendor/htc/mystul/proprietary/etc/firmware/tzapps.b03:/system/etc/firmware/tzapps.b03 \
        vendor/htc/mystul/proprietary/etc/firmware/tzapps.mdt:/system/etc/firmware/tzapps.mdt \
        vendor/htc/mystul/proprietary/etc/firmware/vidc.b00:/system/etc/firmware/vidc.b00 \
        vendor/htc/mystul/proprietary/etc/firmware/vidc.b01:/system/etc/firmware/vidc.b01 \
        vendor/htc/mystul/proprietary/etc/firmware/vidc.b02:/system/etc/firmware/vidc.b02 \
        vendor/htc/mystul/proprietary/etc/firmware/vidc.b03:/system/etc/firmware/vidc.b03 \
        vendor/htc/mystul/proprietary/etc/firmware/vidc.mdt:/system/etc/firmware/vidc.mdt \
        vendor/htc/mystul/proprietary/etc/firmware/vidc_1080p.fw:/system/etc/firmware/vidc_1080p.fw \
        vendor/htc/mystul/proprietary/etc/tfa/deftcoefA.speaker:/system/etc/tfa/deftcoefA.speaker \
        vendor/htc/mystul/proprietary/etc/tfa/playback.config:/system/etc/tfa/playback.config \
        vendor/htc/mystul/proprietary/etc/tfa/playback.eq:/system/etc/tfa/playback.eq \
        vendor/htc/mystul/proprietary/etc/tfa/playback.preset:/system/etc/tfa/playback.preset \
        vendor/htc/mystul/proprietary/etc/tfa/ring.config:/system/etc/tfa/ring.config \
        vendor/htc/mystul/proprietary/etc/tfa/ring.eq:/system/etc/tfa/ring.eq \
        vendor/htc/mystul/proprietary/etc/tfa/ring.preset:/system/etc/tfa/ring.preset \
        vendor/htc/mystul/proprietary/etc/tfa/tfa9887.config:/system/etc/tfa/tfa9887.config \
        vendor/htc/mystul/proprietary/etc/tfa/tfa9887.patch:/system/etc/tfa/tfa9887.patch \
        vendor/htc/mystul/proprietary/etc/tfa/tfa9887.speaker:/system/etc/tfa/tfa9887.speaker \
        vendor/htc/mystul/proprietary/etc/tfa/video.config:/system/etc/tfa/video.config \
        vendor/htc/mystul/proprietary/etc/tfa/video.eq:/system/etc/tfa/video.eq \
        vendor/htc/mystul/proprietary/etc/tfa/video.preset:/system/etc/tfa/video.preset \
        vendor/htc/mystul/proprietary/etc/tfa/voice.config:/system/etc/tfa/voice.config \
        vendor/htc/mystul/proprietary/etc/tfa/voice.eq:/system/etc/tfa/voice.eq \
        vendor/htc/mystul/proprietary/etc/tfa/voice.preset:/system/etc/tfa/voice.preset \
        vendor/htc/mystul/proprietary/vendor/firmware/libpn544_fw.so:/system/vendor/firmware/libpn544_fw.so \
        vendor/htc/mystul/proprietary/lib/hw/sensors.default.so:/system/lib/hw/sensors.default.so \
        vendor/htc/mystul/proprietary/lib/libacdbloader.so:/system/lib/libacdbloader.so \
        vendor/htc/mystul/proprietary/lib/libaudcal.so:/system/lib/libaudcal.so \
        vendor/htc/mystul/proprietary/bin/mm-qcamera-daemon:/system/bin/mm-qcamera-daemon \
        vendor/htc/mystul/proprietary/lib/hw/camera.vendor.msm8960.so:/system/lib/hw/camera.vendor.msm8960.so \
        vendor/htc/mystul/proprietary/lib/libBeautyChat.so:/system/lib/libBeautyChat.so \
        vendor/htc/mystul/proprietary/lib/libcam_oem_plugin.so:/system/lib/libcam_oem_plugin.so \
        vendor/htc/mystul/proprietary/lib/libcameraasd.so:/system/lib/libcameraasd.so \
        vendor/htc/mystul/proprietary/lib/libcameraface.so:/system/lib/libcameraface.so \
        vendor/htc/mystul/proprietary/lib/libcamerapp.so:/system/lib/libcamerapp.so \
        vendor/htc/mystul/proprietary/lib/libchromatix_ov5693_default_video.so:/system/lib/libchromatix_ov5693_default_video.so \
        vendor/htc/mystul/proprietary/lib/libchromatix_ov5693_hdr.so:/system/lib/libchromatix_ov5693_hdr.so \
        vendor/htc/mystul/proprietary/lib/libchromatix_ov5693_hfr.so:/system/lib/libchromatix_ov5693_hfr.so \
        vendor/htc/mystul/proprietary/lib/libchromatix_ov5693_preview.so:/system/lib/libchromatix_ov5693_preview.so \
        vendor/htc/mystul/proprietary/lib/libchromatix_ov5693_zsl.so:/system/lib/libchromatix_ov5693_zsl.so \
        vendor/htc/mystul/proprietary/lib/libchromatix_s5k6a2ya_default_video.so:/system/lib/libchromatix_s5k6a2ya_default_video.so \
        vendor/htc/mystul/proprietary/lib/libchromatix_s5k6a2ya_hdr.so:/system/lib/libchromatix_s5k6a2ya_hdr.so \
        vendor/htc/mystul/proprietary/lib/libchromatix_s5k6a2ya_hfr.so:/system/lib/libchromatix_s5k6a2ya_hfr.so \
        vendor/htc/mystul/proprietary/lib/libchromatix_s5k6a2ya_preview.so:/system/lib/libchromatix_s5k6a2ya_preview.so \
        vendor/htc/mystul/proprietary/lib/libchromatix_s5k6a2ya_zsl.so:/system/lib/libchromatix_s5k6a2ya_zsl.so \
        vendor/htc/mystul/proprietary/lib/libI420colorconvert.so:/system/lib/libI420colorconvert.so \
        vendor/htc/mystul/proprietary/lib/libmmjpeg.so:/system/lib/libmmjpeg.so \
        vendor/htc/mystul/proprietary/lib/liboemcamera.so:/system/lib/liboemcamera.so \
        vendor/htc/mystul/proprietary/lib/libposteffect.so:/system/lib/libposteffect.so \
        vendor/htc/mystul/proprietary/lib/libmm-color-convertor.so:/system/lib/libmm-color-convertor.so \
        vendor/htc/mystul/proprietary/lib/libmmcamera_faceproc.so:/system/lib/libmmcamera_faceproc.so \
        vendor/htc/mystul/proprietary/lib/libmmcamera_frameproc.so:/system/lib/libmmcamera_frameproc.so \
        vendor/htc/mystul/proprietary/lib/libmmcamera_hdr_lib.so:/system/lib/libmmcamera_hdr_lib.so \
        vendor/htc/mystul/proprietary/lib/libmmcamera_image_stab.so:/system/lib/libmmcamera_image_stab.so \
        vendor/htc/mystul/proprietary/lib/libmmcamera_interface2.so:/system/lib/libmmcamera_interface2.so \
        vendor/htc/mystul/proprietary/lib/libmmcamera_rawchipproc.so:/system/lib/libmmcamera_rawchipproc.so \
        vendor/htc/mystul/proprietary/lib/libmmcamera_statsproc31.so:/system/lib/libmmcamera_statsproc31.so \
        vendor/htc/mystul/proprietary/lib/libmmcamera_wavelet_lib.so:/system/lib/libmmcamera_wavelet_lib.so \
        vendor/htc/mystul/proprietary/lib/libmmipl.so:/system/lib/libmmipl.so \
        vendor/htc/mystul/proprietary/lib/libmmstillomx.so:/system/lib/libmmstillomx.so \
        vendor/htc/mystul/proprietary/lib/libgemini.so:/system/lib/libgemini.so \
        vendor/htc/mystul/proprietary/lib/libimage-jpeg-dec-omx-comp.so:/system/lib/libimage-jpeg-dec-omx-comp.so \
        vendor/htc/mystul/proprietary/lib/libimage-jpeg-enc-omx-comp.so:/system/lib/libimage-jpeg-enc-omx-comp.so \
        vendor/htc/mystul/proprietary/lib/libimage-omx-common.so:/system/lib/libimage-omx-common.so \
        vendor/htc/mystul/proprietary/lib/liboemcrypto.so:/system/lib/liboemcrypto.so \
        vendor/htc/mystul/proprietary/bin/netmgrd:/system/bin/netmgrd \
        vendor/htc/mystul/proprietary/bin/qmuxd:/system/bin/qmuxd \
        vendor/htc/mystul/proprietary/lib/libHTC_DIS.so:/system/lib/libHTC_DIS.so \
        vendor/htc/mystul/proprietary/lib/libcsd-client.so:/system/lib/libcsd-client.so \
        vendor/htc/mystul/proprietary/lib/libdiag.so:/system/lib/libdiag.so \
        vendor/htc/mystul/proprietary/lib/libdsi_netctrl.so:/system/lib/libdsi_netctrl.so \
        vendor/htc/mystul/proprietary/lib/libdsutils.so:/system/lib/libdsutils.so \
        vendor/htc/mystul/proprietary/lib/libidl.so:/system/lib/libidl.so \
        vendor/htc/mystul/proprietary/lib/libmllite.so:/system/lib/libmllite.so \
        vendor/htc/mystul/proprietary/lib/libmlplatform.so:/system/lib/libmlplatform.so \
        vendor/htc/mystul/proprietary/lib/libmpl.so:/system/lib/libmpl.so \
        vendor/htc/mystul/proprietary/lib/libmpl_jni.so:/system/lib/libmpl_jni.so \
        vendor/htc/mystul/proprietary/lib/libnetmgr.so:/system/lib/libnetmgr.so \
        vendor/htc/mystul/proprietary/lib/libqc-opt.so:/system/lib/libqc-opt.so \
        vendor/htc/mystul/proprietary/lib/libqcci_legacy.so:/system/lib/libqcci_legacy.so \
        vendor/htc/mystul/proprietary/lib/libqdi.so:/system/lib/libqdi.so \
        vendor/htc/mystul/proprietary/lib/libqdp.so:/system/lib/libqdp.so \
        vendor/htc/mystul/proprietary/lib/libqmi.so:/system/lib/libqmi.so \
        vendor/htc/mystul/proprietary/lib/libqmi_cci.so:/system/lib/libqmi_cci.so \
        vendor/htc/mystul/proprietary/lib/libqmi_client_qmux.so:/system/lib/libqmi_client_qmux.so \
        vendor/htc/mystul/proprietary/lib/libqmi_common_so.so:/system/lib/libqmi_common_so.so \
        vendor/htc/mystul/proprietary/lib/libqmi_csi.so:/system/lib/libqmi_csi.so \
        vendor/htc/mystul/proprietary/lib/libqmi_encdec.so:/system/lib/libqmi_encdec.so \
        vendor/htc/mystul/proprietary/lib/libqmiservices.so:/system/lib/libqmiservices.so \
        vendor/htc/mystul/proprietary/lib/libril-qc-qmi-1.so:/system/lib/libril-qc-qmi-1.so \
        vendor/htc/mystul/proprietary/lib/libril-qcril-hook-oem.so:/system/lib/libril-qcril-hook-oem.so \
        vendor/htc/mystul/proprietary/lib/libdrmdecrypt.so:/system/lib/libdrmdecrypt.so \
        vendor/htc/mystul/proprietary/lib/libdrmfs.so:/system/lib/libdrmfs.so \
        vendor/htc/mystul/proprietary/lib/libdrmtime.so:/system/lib/libdrmtime.so \
        vendor/htc/mystul/proprietary/vendor/lib/libwvdrm_L1.so:/system/vendor/lib/libwvdrm_L1.so \
        vendor/htc/mystul/proprietary/vendor/lib/libwvm.so:/system/vendor/lib/libwvm.so \
        vendor/htc/mystul/proprietary/vendor/lib/libWVStreamControlAPI_L1.so:/system/vendor/lib/libWVStreamControlAPI_L1.so \
        vendor/htc/mystul/proprietary/vendor/lib/egl/eglsubAndroid.so:/system/vendor/lib/egl/eglsubAndroid.so \
        vendor/htc/mystul/proprietary/vendor/lib/egl/libEGL_adreno.so:/system/vendor/lib/egl/libEGL_adreno.so \
        vendor/htc/mystul/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:/system/vendor/lib/egl/libGLESv1_CM_adreno.so \
        vendor/htc/mystul/proprietary/vendor/lib/egl/libGLESv2S3D_adreno.so:/system/vendor/lib/egl/libGLESv2S3D_adreno.so \
        vendor/htc/mystul/proprietary/vendor/lib/egl/libGLESv2_adreno.so:/system/vendor/lib/egl/libGLESv2_adreno.so \
        vendor/htc/mystul/proprietary/vendor/lib/egl/libq3dtools_adreno.so:/system/vendor/lib/egl/libq3dtools_adreno.so \
        vendor/htc/mystul/proprietary/vendor/lib/libC2D2.so:/system/vendor/lib/libC2D2.so \
        vendor/htc/mystul/proprietary/vendor/lib/libCB.so:/system/vendor/lib/libCB.so \
        vendor/htc/mystul/proprietary/vendor/lib/libOpenCL.so:/system/vendor/lib/libOpenCL.so \
        vendor/htc/mystul/proprietary/vendor/lib/libOpenVG.so:/system/vendor/lib/libOpenVG.so \
        vendor/htc/mystul/proprietary/vendor/lib/libadreno_utils.so:/system/vendor/lib/libadreno_utils.so \
        vendor/htc/mystul/proprietary/vendor/lib/libc2d2_a3xx.so:/system/vendor/lib/libc2d2_a3xx.so \
        vendor/htc/mystul/proprietary/vendor/lib/libc2d2_z180.so:/system/vendor/lib/libc2d2_z180.so \
        vendor/htc/mystul/proprietary/vendor/lib/libgsl.so:/system/vendor/lib/libgsl.so \
        vendor/htc/mystul/proprietary/vendor/lib/libllvm-a3xx.so:/system/vendor/lib/libllvm-a3xx.so \
        vendor/htc/mystul/proprietary/vendor/lib/libllvm-arm.so:/system/vendor/lib/libllvm-arm.so \
        vendor/htc/mystul/proprietary/vendor/lib/libsc-a2xx.so:/system/vendor/lib/libsc-a2xx.so \
        vendor/htc/mystul/proprietary/vendor/lib/libsc-a3xx.so:/system/vendor/lib/libsc-a3xx.so \
        vendor/htc/mystul/proprietary/bin/netmgrd:/system/bin/netmgrd \
        vendor/htc/mystul/proprietary/bin/qmuxd:/system/bin/qmuxd \
        vendor/htc/mystul/proprietary/lib/libdiag.so:/system/lib/libdiag.so \
        vendor/htc/mystul/proprietary/lib/libdsi_netctrl.so:/system/lib/libdsi_netctrl.so \
        vendor/htc/mystul/proprietary/lib/libdsutils.so:/system/lib/libdsutils.so \
        vendor/htc/mystul/proprietary/lib/libidl.so:/system/lib/libidl.so \
        vendor/htc/mystul/proprietary/lib/libqdi.so:/system/lib/libqdi.so \
        vendor/htc/mystul/proprietary/lib/libqdp.so:/system/lib/libqdp.so \
        vendor/htc/mystul/proprietary/lib/libqmi_cci.so:/system/lib/libqmi_cci.so \
        vendor/htc/mystul/proprietary/lib/libqmi_common_so.so:/system/lib/libqmi_common_so.so \
        vendor/htc/mystul/proprietary/lib/libqmi_csi.so:/system/lib/libqmi_csi.so \
        vendor/htc/mystul/proprietary/lib/libqmi_encdec.so:/system/lib/libqmi_encdec.so \
        vendor/htc/mystul/proprietary/lib/libqmiservices.so:/system/lib/libqmiservices.so \
        vendor/htc/mystul/proprietary/lib/libqmi.so:/system/lib/libqmi.so \
        vendor/htc/mystul/proprietary/lib/libnetmgr.so:/system/lib/libnetmgr.so \
        vendor/htc/mystul/proprietary/lib/libril-qc-qmi-1.so:/system/lib/libril-qc-qmi-1.so \
        vendor/htc/mystul/proprietary/lib/libril-qcril-hook-oem.so:/system/lib/libril-qcril-hook-oem.so
